# Learn more at https://jupyterbook.org/customize/config.html

title: Modelling energy systems
author: ""
# logo: images/logo-text.png

execute:
  execute_notebooks: cache  # Cache results of notebook execution and re-execute if a code cell changes

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - attrs_inline

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    html_js_files: [ ['https://cdn.usefathom.com/script.js', {'defer': 'defer', 'data-site': 'QUYIGXRL'}] ]
    myst_substitutions:
      circle_params: '<span class="circ circ-params">P</span>'
      circle_vars: '<span class="circ circ-variables">V</span>'
      circle_obj: '<span class="circ circ-objective">O</span>'
      circle_constr: '<span class="circ circ-constraints">C</span>'
      labeled_circle_params: '<span class="circ circ-params">P</span> <span class="circ-text params">Parameters</span>'
      labeled_circle_vars: '<span class="circ circ-variables">V</span> <span class="circ-text variables">Variables</span>'
      labeled_circle_obj: '<span class="circ circ-objective">O</span> <span class="circ-text objective">Objective</span>'
      labeled_circle_constr: '<span class="circ circ-constraints">C</span> <span class="circ-text constraints">Constraints</span>'

exclude_patterns: [.pixi, Thumbs.db, .DS_Store, README.md, "**.ipynb_checkpoints", "**BUILD-IGNORE**", "_assets"]

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/sjpfenninger/modelling-energy-systems  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_issues_button: true
  # use_repository_button: true
  # favicon: images/favicon.ico
  extra_footer: |
    <p><a href="/reference/about">Authors</a> | License: <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> (please link to the <a href="https://www.modelling-energy-systems.org/">main page</a> for attribution) | <a href="https://github.com/sjpfenninger/modelling-energy-systems">Source code</a></p>
