name: modelling-energy-systems-2025-10
channels:
    - conda-forge/label/calliope_dev
    - conda-forge
    - gurobi
dependencies:
    - python=3.12
    - matplotlib=3.10.5
    - seaborn=0.13.2
    - jupyterlab
    - glpk=5.0
    - ipopt=3.14.16
    - gurobi
    - calliope=0.7.0dev7
    - pyproj
    - pip
    - pip:
        - optimutils
        - calligraph==0.1.1.dev7
